### ISSUE TITLE
"ValueError: Word to be hyphenated may have at most 100 characters." 

### ISSUE THREAD

**Issue by shahshaswat2** [erinhengel/Textatistic#3]
I'm getting "ValueError: Word to be hyphenated may have at most 100 characters."  I'm trying to get the text score of an Ebook, it works fine when I do for one book, but when I try to run a loop to get the x.dict() (all scores) of all books and to append in a new list for each book, it gives me this error. 

Is there a fix around with this? I couldn't find any documentation related to this issue.

**Comment by erinhengel** [comment]
Unfortunately, I'm pretty sure this is an issue with the dependency PyHyphen—it sounds like it doesn't hyphenate words of 100 characters or more.
